FROM n8nio/n8n:latest

# Variables de entorno para Render
ENV N8N_HOST=0.0.0.0
ENV N8N_PROTOCOL=https
ENV N8N_BASIC_AUTH_ACTIVE=true
ENV N8N_BASIC_AUTH_USER=admin
ENV N8N_BASIC_AUTH_PASSWORD=MiPassword123
ENV N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS=false
ENV GENERIC_TIMEZONE=America/Lima

EXPOSE 5678

USER node

CMD ["n8n"]
