services:
  - type: web
    name: n8n
    env: docker
    dockerfilePath: ./Dockerfile
    plan: free
    envVars:
      - key: N8N_HOST
        value: n8n.labinnovauai.dedyn.io
      - key: N8N_PROTOCOL
        value: https
      - key: NODE_ENV
        value: production
      - key: WEBHOOK_URL
        value: https://n8n.labinnovauai.dedyn.io/
      - key: N8N_BASIC_AUTH_ACTIVE
        value: true
      - key: N8N_BASIC_AUTH_USER
        value: admin
      - key: N8N_BASIC_AUTH_PASSWORD
        value: tu_password_seguro
      - key: GENERIC_TIMEZONE
        value: America/Lima
      - key: DB_TYPE
        value: sqlite
    disk:
      name: n8n-data
      mountPath: /home/node/.n8n
      sizeGB: 1